import os


"""
Django settings for lizzie project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2o&utcn)$(g!x0bd&!+6vpqk$&l%_#p)*l_#x_29rdl_t@4=x*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',

    'lizapp',
    'reviews',
    'newsletter',
    'accounts',
    'chat',

    'rest_framework',
    'rest_framework.authtoken',

    'drf_yasg',
    
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'dj_rest_auth',
    'dj_rest_auth.registration',

    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', #multilan
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lizzie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

JAZZMIN_SETTINGS = {
    "site_title": "Lizzie Admin",
    "site_header": "Lizzie Mental Health Support",
    "welcome_sign": "Ласкаво просимо в панель керування!",
    "login_logo": "images/logo2.jpg",
    "site_brand": "Lizzie",
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["lizapp.YourModel"],
    "icons": {
        "lizapp.YourModel": "fas fa-heart",
    },
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cerulean",
    "dark_mode_theme": "darkly",
    "navbar_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "footer_small_text": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme_switcher": True,
    "navbar_fixed": False,
    "footer_fixed": False,
    "layout_boxed": False,
    "layout_fixed_sidebar": False,
    "layout_fixed_header": False,
    "layout_fixed_footer": False,
    "sidebar_background": None,
    "sidebar_main_bg": None,
    "sidebar_nav_child_bg": None,
    "sidebar_nav_child_active_color": None,
    "sidebar_nav_child_active_bg": None,
    "sidebar_nav_child_hover_color": None,
    "sidebar_nav_child_hover_bg": None,
    "disable_visual_filters": False,
}

WSGI_APPLICATION = 'lizzie.wsgi.application'
ASGI_APPLICATION = 'lizzie.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lizzie_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'MySQL-8.2',
        'PORT': '3306',
    }
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = 'UTC'

USE_I18N = True

TIME_ZONE = 'Europe/Kiev'
USE_TZ = True

LOGIN_REDIRECT_URL = '/'

gettext = lambda s: s
LANGUAGES = (
    ('en', gettext('English')),
    ('uk', gettext('Ukrainian')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 1
}

SITE_ID = 1





# Обов’язкова наявність email
ACCOUNT_EMAIL_REQUIRED = True

# Підтвердження пошти (опції: "mandatory", "optional", "none")
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# Обов'язкове поле username (якщо їх використовуєте)
ACCOUNT_USERNAME_REQUIRED = True

# Метод аутентифікації: за username або email або обома
ACCOUNT_AUTHENTICATION_METHOD = "username_email"



# В production-додатках налаштуйте SMTP або інший email backend, наприклад:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@example.com'
# EMAIL_HOST_PASSWORD = 'your-email-password'

# Використовуємо SMTP бекенд для відправки реальних листів
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'           # SMTP-сервер, наприклад, для Gmail
EMAIL_PORT = 587                        # Порт для TLS
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'testforconfirm1@gmail.com'  # Ваша email-адреса
EMAIL_HOST_PASSWORD = 'irmr pfso glow aocn'  # Пароль або app password для Gmail


ACCOUNT_UNIQUE_EMAIL = False
ACCOUNT_LOGIN_METHODS = ['username']
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']


REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'accounts.serializers.CustomRegisterSerializer',
}

 
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [(os.environ.get("REDIS_HOST", "localhost"), int(os.environ.get("REDIS_PORT", 6379)))],
#         },
#     },
# }

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}
