# Generated by Django 5.1.7 on 2025-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введіть дійсну електронну адресу', max_length=254, unique=True, verbose_name='Поштова адреса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Користувацька пошта',
                'verbose_name_plural': 'Користувацькі пошти',
            },
        ),
    ]
