# Generated by Django 5.1.7 on 2025-04-23 16:00

import newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(help_text='Введіть дійсну електронну адресу', max_length=254, unique=True, validators=[newsletter.models.validate_email_dns], verbose_name='Поштова адреса'),
        ),
    ]
