# Generated by Django 5.1.7 on 2025-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назва зображення', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Опис зображення')),
                ('image_file', models.ImageField(blank=True, help_text='Завантажте зображення', null=True, upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Дата завантаження')),
                ('category', models.CharField(blank=True, help_text="Категорія зображення (наприклад, 'logo', 'photo')", max_length=100)),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Зображення',
            },
        ),
    ]
