# Generated by Django 5.1.7 on 2025-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='surname',
            field=models.CharField(default='No last name', max_length=100, verbose_name='name'),
        ),
    ]
