# Generated by Django 5.1.7 on 2025-04-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lizapp', '0002_reviews_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
