# Generated by Django 5.1.7 on 2025-04-23 16:00

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='surname',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=12, validators=[reviews.models.validate_name], verbose_name='Ім’я'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=5000, validators=[reviews.models.validate_text], verbose_name='Текст'),
        ),
    ]
