# Generated by Django 5.1.7 on 2025-05-06 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата та час оновлення'),
        ),
    ]
