# Generated by Django 5.1.7 on 2025-05-13 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_created_at_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
